<?php

namespace ControlPanelBundle\Repository;

/**
 * TipoMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoMovimientoInventario extends \Doctrine\ORM\EntityRepository
{
}
