<?php

namespace InventarioBundle\Repository;

use AdministracionBundle\Entity\Bodega;
use AdministracionBundle\Entity\Material;
use Doctrine\ORM\EntityRepository;
use InventarioBundle\Entity\InventarioMaterial;

/**
 * Inventario Material
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioMaterialRepository extends EntityRepository
{
    /**
     * @param $material
     * @param $bodega
     * @return InventarioMaterial
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByInventario(Material $material, Bodega $bodega) {
        return $this->createQueryBuilder('p')
            ->where('p.material = :material')
            ->andWhere('p.bodega = :bodega')
            ->setParameter('material', $material)
            ->setParameter('bodega', $bodega)
            ->getQuery()
            ->getOneOrNullResult();
    }


    public function findByBodega(Bodega $bodega) {
        return $this->createQueryBuilder('p')
            ->where('p.bodega = :bodega')
            ->andWhere('p.cantidad != 0')
            ->setParameter('bodega', $bodega)
            ->getQuery()
            ->getResult();
    }

    public function findByMaterial(Material $material) {
        return $this->createQueryBuilder('p')
            ->where('p.material = :material')
            ->andWhere('p.cantidad != 0')
            ->setParameter('material', $material)
            ->getQuery()
            ->getResult();
    }
}
