<?php

namespace InventarioBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * Inventario Material
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventarioMaterialRepository extends EntityRepository
{
}
