<?php

namespace InventarioBundle\Repository;

/**
 * MovimientoInventarioDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoInventarioDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
