<?php

namespace InventarioBundle\Repository;

use AdministracionBundle\Entity\Material;

/**
 * MovimientoMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoMaterialRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Material $material
     * @param \DateTime $date
     * @return array
     */
    public function findByMaterialAfterDate(Material $material, \DateTime $date) {
        return $this->createQueryBuilder('m')
            ->where("m.material = :material")
            ->andWhere("m.fecha > :date")
            ->setParameter('material', $material)
            ->setParameter('date', $date)
            ->getQuery()
            ->getArrayResult();
    }
}
