<?php

namespace InventarioBundle\Repository;

/**
 * MovimientoInventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoInventarioRepository extends \Doctrine\ORM\EntityRepository
{
}
