<?php

namespace InventarioBundle\Repository;

/**
 * MovimientoMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
